### ISSUE TITLE
Improve the definitions feature

### ISSUE THREAD

**Issue by ncrocfer** [ovh/celery-director#130]
Some improvements have to be done:

**V1**
- include the pytz package in the requirements.txt
- use ISO8601 date format in the next_run key
- the pagination is not useful, remove it
- use the /api/definitions endpoint

**V2**
- add a UI view to display the list of workflows

**V3**
- allow the user to execute a workflow using the UI

**Comment by anthonyolea** [comment]
Updates regarding this issue since the merge of PR #150:

**V1**
- ~~include the pytz package in the requirements.txt~~
  The package _pytz was using to compute next_run key, see below._
- ~~use ISO8601 date format in the next_run key~~
  The _next_run value was unreliable, removed._
- ~~the pagination is not useful, remove it~~
  _Done._
- ~~use the /api/definitions endpoint~~
  _Done._

**Comment by ncrocfer** [comment]
Closing this issue as V2 & V3 features are now available.
